name: Java CI with Maven and Docker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  regression-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose
        run: |
          docker compose up --build -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for containers to be healthy..."
          sleep 15
          docker ps

      - name: Run Maven Unit Tests
        id: run_tests
        run: mvn clean test

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
